#pragma once

namespace axelynx
{
	namespace KEY
	{
		const int BACK           =0x08;
		const int TAB            =0x09;
		const int CLEAR          =0x0C;
		const int RETURN         =0x0D;
		const int SHIFT          =0x10;
		const int CONTROL        =0x11;
		const int MENU           =0x12;
		const int PAUSE          =0x13;
		const int CAPITAL        =0x14;
		const int KANA           =0x15;
		const int HANGEUL        =0x15 ; /* old name - should be here for compatibility */
		const int HANGUL         =0x15;
		const int JUNJA          =0x17;
		const int FINAL          =0x18;
		const int HANJA          =0x19;
		const int KANJI          =0x19;
		const int ESCAPE         =0x1B;
		const int CONVERT        =0x1C;
		const int NONCONVERT     =0x1D;
		const int ACCEPT         =0x1E;
		const int MODECHANGE     =0x1F;
		const int SPACE          =0x20;
		const int PRIOR          =0x21;
		const int NEXT           =0x22;
		const int END            =0x23;
		const int HOME           =0x24;
		const int LEFT           =0x25;
		const int UP             =0x26;
		const int RIGHT          =0x27;
		const int DOWN           =0x28;
		const int SELECT         =0x29;
		const int PRINT          =0x2A;
		const int EXECUTE        =0x2B;
		const int SNAPSHOT       =0x2C;
		const int INSERT         =0x2D;
//		const int DELETE		 =0x2E;
		const int HELP           =0x2F;
		const int LWIN           =0x5B;
		const int RWIN           =0x5C;
		const int APPS           =0x5D;
		const int SLEEP          =0x5F;
		const int NUMPAD0        =0x60;
		const int NUMPAD1        =0x61;
		const int NUMPAD2        =0x62;
		const int NUMPAD3        =0x63;
		const int NUMPAD4        =0x64;
		const int NUMPAD5        =0x65;
		const int NUMPAD6        =0x66;
		const int NUMPAD7        =0x67;
		const int NUMPAD8        =0x68;
		const int NUMPAD9        =0x69;
		const int MULTIPLY       =0x6A;
		const int ADD            =0x6B;
		const int SEPARATOR      =0x6C;
		const int SUBTRACT       =0x6D;
		const int DECIMAL        =0x6E;
		const int DIVIDE         =0x6F;
		const int F1             =0x70;
		const int F2             =0x71;
		const int F3             =0x72;
		const int F4             =0x73;
		const int F5             =0x74;
		const int F6             =0x75;
		const int F7             =0x76;
		const int F8             =0x77;
		const int F9             =0x78;
		const int F10            =0x79;
		const int F11            =0x7A;
		const int F12            =0x7B;
		const int F13            =0x7C;
		const int F14            =0x7D;
		const int F15            =0x7E;
		const int F16            =0x7F;
		const int F17            =0x80;
		const int F18            =0x81;
		const int F19            =0x82;
		const int F20            =0x83;
		const int F21            =0x84;
		const int F22            =0x85;
		const int F23            =0x86;
		const int F24            =0x87;
		const int NUMLOCK        =0x90;
		const int SCROLL         =0x91;
	}
}